import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // The naming rules in CLAUDE.md, as far as a linter can enforce them.
      "id-denylist": [
        "error",
        "res",
        "req",
        "e",
        "err",
        "idx",
        "tmp",
        "val",
        "db",
        "usr",
        "cfg",
        "ctx",
        "arr",
        "obj",
        "fn",
        "cb",
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      eqeqeq: ["error", "always"],
      "prefer-const": "error",
      "no-var": "error",
      // Server-side logging of unexpected failures is deliberate; anything else is a leftover.
      "no-console": ["warn", { allow: ["error", "warn"] }],
      complexity: ["warn", 10],
      "max-depth": ["warn", 3],
      "max-lines-per-function": ["warn", { max: 120, skipBlankLines: true, skipComments: true }],
    },
  },
  {
    // A describe block is a list of tests, not a function to hold in your head, so the length limit
    // says nothing useful about it. Everything else, including the naming rules, still applies.
    files: ["**/*.test.ts", "**/*.test.tsx", "e2e/**"],
    rules: {
      "max-lines-per-function": "off",
    },
  },
  {
    // A build script run by hand from a terminal: its output is the point of running it.
    files: ["scripts/**"],
    rules: {
      "no-console": "off",
    },
  },
  {
    // Generated by the shadcn CLI and kept as delivered, so the project rules do not apply.
    files: ["src/components/ui/**"],
    rules: {
      "id-denylist": "off",
      "max-lines-per-function": "off",
    },
  },
  prettier,
  globalIgnores([".next/**", "out/**", "build/**", "next-env.d.ts", "coverage/**"]),
]);

export default eslintConfig;
